members = [
    "crates/primitives"
]

[package]
name = "chain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
sha2 = "0.10"
rand = "0.8.5"
primitives = {path = "crates/primitives"}

[[bin]]
name = "main"
path = "src/main.rs"
